### ISSUE TITLE
Updates/issues

### ISSUE THREAD

**Issue by JamesHenry** [guillempuche/nx-expo-next-tamagui#1]
Following on from the comments you made on the issue, I pulled down your repo to have a look.

Your release config is currently invalid, you have nested version within changelog. Additionally, the git config within changelog is unnecessary as you are just repeating the default values.

In your case your release config only needs to be:

```json
"release": {
    "projects": [
      "packages/*"
    ],
    "version": {
      "conventionalCommits": true
    }
  },
```

Please be aware that you have some other issues going on:

1. You have ignored your whole `.yarn` directory, so your yarn config is invalid and cannot run because of `yarnPath: .yarn/releases/yarn-4.1.0.cjs` and the release not existing. Consult the yarn docs for how to handle the .yarn directory, you are not supposed to ignore the whole thing.
2. You are extending from `expo/tsconfig.base` in your root tsconfig.json, which does not exist. This is what is causing the false positive on the changelog renderer resolution FYI, we are swallowing the real error as discussed on the Nx repo, and I will fix that, but you will need to address this actual on your side before it works.
3. More minor but still relevant, your formatting is currently inconsistent. Your tsconfig.base.json is using tabs and other files aren't. This will lead to a bit of noise in your version diffs when `formatFiles()` is applied behind the scenes.

Hope that helps!

**Comment by guillempuche** [comment]
Ohh! Amazing advices!

In case of linting, I'm starting to use Biome as a replacement of Prettier and Eslint.

**Comment by guillempuche** [comment]
Solved
