### ISSUE TITLE
App is not launching

### ISSUE THREAD

**Issue by kalingaCoder** [guillempuche/nx-expo-next-tamagui#3]
PS C:\code\dhrona-x> **yarn exec nx run expo:start**

 NX   Running target start for project expo and 2 tasks it depends on:

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

> nx run expo:ensure-symlink

> nx run expo:sync-deps

info Dependencies for 'expo' are up to date! No changes made.

> nx run expo:start

Packager is ready at http://localhost:8081
Starting project at C:\code\dhrona-x\apps\expo
(node:5792) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Using src/app as the root directory for Expo Router.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ██▀▀█▀▄██ ▄▄▄▄▄ █
█ █   █ █  ▀█ ▀█▄▄█ █   █ █
█ █▄▄▄█ █▀  █▄▀▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█▄█▄█▄▄▄▄▄▄▄█
█  █▀  ▄███▄█▄▀▄ ███ ▀▄▄ ▄█
█ ▀██ ▀▄▄▄ ▄█▀██ ▀▀ █▄  ▀██
█▀██▀█▀▄▄▀▀▀▄▀█▄▀▄▀▄▀▀▄ ▀██
███ ▀█ ▄▀ █▄ ▄██▄▄▄█▄▀ ▀███
█▄▄█▄█▄▄▄ ▀▀█▄▀▄▄ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▀▀█▀█▀▀ █▄█ ▀▀▀▀█
█ █   █ █▄ ▄▄▀▄ █▄▄ ▄▄▀   █
█ █▄▄▄█ █▀▀▄ ▄ ▄▄██▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄███▄▄█████▄▄▄▄▄▄█

› Metro waiting on exp://192.168.1.8:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
› Opening exp://192.168.1.8:8081 on Pixel_5_API_34
› Press ? │ show all commands
Using src/app as the root directory for Expo Router.
transform[stdout]:  native  |              [...missing]   ·    3 found   ·    3 opt   ·    1 flat  6317ms
transform[stdout]:  native  |                     modal   ·    1 found   ·    1 opt   ·    1 flat  7578ms
transform[stdout]:  native  |                layout.web   ·    5 found   ·    3 opt   ·    1 flat    61ms
transform[stdout]:  native  |                    screen   ·    5 found   ·    3 opt   ·    0 flat    54ms
transform[stdout]:  native  |                    screen   ·    1 found   ·    0 opt   ·    0 flat    19ms
transform[stdout]:  native  |                    screen   ·    8 found   ·    1 opt   ·    0 flat    17ms
transform[stdout]:  native  |                      Link   ·    1 found   ·    0 opt   ·    0 flat    14ms
transform[stdout]:  native  |                SimpleCard   ·    6 found   ·    3 opt   ·    1 flat   113ms
Android Bundled 67525ms (C:\code\dhrona-x\node_modules\expo-router\entry.js)
Android Bundled 57904ms (C:\code\dhrona-x\node_modules\expo-router\entry.js)

Displays below error on Android studio: _java.lang.exception: Unable to load all assets._

**Comment by guillempuche** [comment]
What did you modify on Expo or Tamgui config? Are you using NodeJS >=20?

*I haven't tested the repo on Windows machine

**Comment by FranciscoKloganB** [comment]
I have the same issue, on Node 20; So it might be related.

What I ended up doing, was make all tasks depend on `expo:sync-deps`, which itself depends on `expo:ensure-symlink`. It's slower because it runs sequentially, but works for me.

**Comment by kalingaCoder** [comment]
> What did you modify on Expo or Tamgui config? Are you using NodeJS >=20?
> 
> *I haven't tested the repo on Windows machine

It was a clean code, no changes were done

**Comment by guillempuche** [comment]
@FranciscoKloganB, what did you change in `apps/expo/project.json` https://github.com/guillempuche/nx-expo-next-tamagui/blob/main/apps/expo/project.json#L7?

```json
	...
	"targets": {
		"start": {
			"executor": "@nx/expo:start",
			"dependsOn": ["ensure-symlink", "sync-deps"],
			"options": {
				"port": 8081,
				"clear": true
			}
		},
	...
```

For me, it's still working. My logs:

```sh
yarn exec nx run expo:start

 NX   Running target start for project expo and 2 tasks it depends on:

————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run expo:ensure-symlink


> nx run expo:sync-deps

                       info Dependencies for 'expo' are up to date! No changes made.

> nx run expo:start

Packager is ready at http://localhost:8081
Starting project at /Users/guillem/programacio/codi/cites/nx-expo-next-tamagui/apps/expo
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Using src/app as the root directory for Expo Router.
The following packages should be updated for best compatibility with the installed expo version:
  expo-router@3.4.8 - expected version: ~3.4.10
  react-native@0.73.4 - expected version: 0.73.6
  react-native-safe-area-context@4.9.0 - expected version: 4.8.2
  expo-splash-screen@0.26.4 - expected version: ~0.26.5
  @types/react-dom@18.2.14 - expected version: ~18.0.10
Your project may not work correctly until you install the correct versions of the packages.
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █ ██▀▀ █▄██ ▄▄▄▄▄ █
█ █   █ █  ▀█ ▀▄▀▄█ █   █ █
█ █▄▄▄█ █▀  █▄ ▀▄██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█ █▄█▄▄▄▄▄▄▄█
█  ▀▀  ▄███▄█▄█▄ ███ ▀▄▄ ▄█
█▀▀ ▀ ▄▄▀  ▄█▀▄█ ▀▀ █▄  ▀██
█ ▄█▄▀▀▄█▀▀▀▄▀█▄▀▄▀▄▀▀▄ ▀██
███ ▀ ▀▄▄▄▄█ ▄██▄▄▄█▄▀ ▀███
█▄▄█▄██▄▄ █▄█▄▀▄▄ ▄▄▄ ▀ ▄▄█
█ ▄▄▄▄▄ █▀▄ █▀██▀ █▄█ ▀▀▀██
█ █   █ █▄▀ ▄ █▄█▄▄ ▄▄▀ ▀▀█
█ █▄▄▄█ █▀▀▄ ▄██▄██▄▀█▀▀ ██
█▄▄▄▄▄▄▄█▄▄▄███▄████▄▄▄▄▄▄█

› Metro waiting on exp://192.168.1.251:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web
...
```

**Comment by FranciscoKloganB** [comment]
Nothing. From this repository only a fresh download, but using NodeJS 22.1.0 instead of NodeJS 18.x.x;

**Comment by guillempuche** [comment]
@kalingaCoder, I close the issue.

After trying Node 20 or 22 and still with the issue, you can reopen with explanation about your settings and changes of the original repo.
